title: Sumit Agarwal
url: "https://iamagarwalsumit.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume_sumit_agarwal.pdf"
 - name: "Contact"
   link: "contact"

theme: jekyll-theme-slate
